package homework.exercise10;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.*;

public class Calculator extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setLocationRelativeTo(null);
        addKeyListener(this);
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
    }

    private static final int NONE = 0;
    private static final int PLUS = 1;
    private static final int REST = 2;
    private static final int MULT = 3;
    private static final int DIV = 4;

    private double previousNum;

    private int operation = NONE;

    private boolean cleanOnNextDigit = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenField = new javax.swing.JTextField();
        buttonsPanel = new javax.swing.JPanel();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonMult = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonRest = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonDot = new javax.swing.JButton();
        buttonSum = new javax.swing.JButton();
        buttonResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setMinimumSize(new java.awt.Dimension(350, 400));
        setResizable(false);

        screenField.setEditable(false);
        screenField.setBackground(new java.awt.Color(255, 255, 255));
        screenField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        screenField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        screenField.setText("0");
        screenField.setAutoscrolls(false);
        screenField.setFocusable(false);
        screenField.setMinimumSize(new java.awt.Dimension(64, 45));
        screenField.setOpaque(true);
        getContentPane().add(screenField, java.awt.BorderLayout.NORTH);

        buttonsPanel.setFocusable(false);
        buttonsPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonsPanel.setMinimumSize(new java.awt.Dimension(324, 300));
        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new java.awt.GridLayout(4, 4));

        button7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button7.setText("7");
        button7.setFocusable(false);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button7);

        button8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button8.setText("8");
        button8.setFocusable(false);
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button8);

        button9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button9.setText("9");
        button9.setFocusable(false);
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button9);

        buttonDiv.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonDiv.setText("÷");
        buttonDiv.setFocusable(false);
        buttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonDiv);

        button4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button4.setText("4");
        button4.setFocusable(false);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button4);

        button5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button5.setText("5");
        button5.setFocusable(false);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button5);

        button6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button6.setText("6");
        button6.setFocusable(false);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button6);

        buttonMult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonMult.setText("×");
        buttonMult.setFocusable(false);
        buttonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonMult);

        button1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button1.setText("1");
        button1.setFocusable(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button1);

        button2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button2.setText("2");
        button2.setFocusable(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button2);

        button3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button3.setText("3");
        button3.setFocusable(false);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button3);

        buttonRest.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonRest.setText("−");
        buttonRest.setFocusable(false);
        buttonRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonRest);

        buttonC.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        buttonC.setText("C");
        buttonC.setFocusable(false);
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonC);

        button0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        button0.setText("0");
        button0.setFocusable(false);
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        buttonsPanel.add(button0);

        buttonDot.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        buttonDot.setText(".");
        buttonDot.setFocusable(false);
        buttonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDotActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonDot);

        buttonSum.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonSum.setText("+");
        buttonSum.setFocusable(false);
        buttonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumActionPerformed(evt);
            }
        });
        buttonsPanel.add(buttonSum);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.CENTER);

        buttonResult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonResult.setFocusable(false);
        buttonResult.setLabel("=");
        buttonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResultActionPerformed(evt);
            }
        });
        getContentPane().add(buttonResult, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        appendDigit(1);
    }//GEN-LAST:event_button1ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        appendDigit(7);
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        appendDigit(8);
    }//GEN-LAST:event_button8ActionPerformed

    private void buttonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivActionPerformed
        operation(DIV);
    }//GEN-LAST:event_buttonDivActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        appendDigit(9);
    }//GEN-LAST:event_button9ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        appendDigit(4);
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        appendDigit(5);
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        appendDigit(6);
    }//GEN-LAST:event_button6ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        appendDigit(2);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        appendDigit(3);
    }//GEN-LAST:event_button3ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        if (!isEmpty()) {
            appendDigit(0);
        }
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDotActionPerformed
        if (cleanOnNextDigit) {
            cleanOnNextDigit = false;
            screenField.setText("0.");
        } else {
            String text = screenField.getText();
            if (!text.contains(".")) {
                screenField.setText(text + '.');
            }
        }
    }//GEN-LAST:event_buttonDotActionPerformed

    private void buttonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultActionPerformed
        operation(MULT);
    }//GEN-LAST:event_buttonMultActionPerformed

    private void buttonRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestActionPerformed
        operation(REST);
    }//GEN-LAST:event_buttonRestActionPerformed

    private void buttonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumActionPerformed
        operation(PLUS);
    }//GEN-LAST:event_buttonSumActionPerformed

    private void buttonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResultActionPerformed
        if (operation != NONE) {
            double num2 = Double.parseDouble(screenField.getText());
            double result = 0;
            switch (operation) {
                case DIV:
                    if (num2 == 0d) {
                        JOptionPane.showMessageDialog(this, "División por 0", "Error", JOptionPane.ERROR_MESSAGE);
                        reset();
                        return;
                    }
                    result = previousNum / num2;
                    break;
                case MULT:
                    result = previousNum * num2;
                    break;
                case REST:
                    result = previousNum - num2;
                    break;
                case PLUS:
                    result = previousNum + num2;
                    break;
            }
            screenField.setText(String.valueOf(round(result)));
            operation = NONE;
        }
    }//GEN-LAST:event_buttonResultActionPerformed

    private double round(double value) {
        return (double) Math.round(value * 100000d) / 100000d;
    }

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        reset();
    }//GEN-LAST:event_buttonCActionPerformed

    public void reset() {
        previousNum = 0;
        operation = NONE;
        screenField.setText("0");
    }

    public void appendDigit(int number) {
        if (cleanOnNextDigit) {
            cleanOnNextDigit = false;
            screenField.setText(String.valueOf(number));
        } else if (isEmpty()) {
            screenField.setText(String.valueOf(number));
        } else {
            String value = screenField.getText();
            screenField.setText(value + number);
        }
    }

    public boolean isEmpty() {
        return screenField.getText().equals("0");
    }

    public void operation(int operation) {
        previousNum = Double.parseDouble(screenField.getText());
        this.operation = operation;
        cleanOnNextDigit = true;
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        switch (e.getKeyChar()) {
            case '0':
                button0.doClick();
                break;
            case '1':
                button1.doClick();
                break;
            case '2':
                button2.doClick();
                break;
            case '3':
                button3.doClick();
                break;
            case '4':
                button4.doClick();
                break;
            case '5':
                button5.doClick();
                break;
            case '6':
                button6.doClick();
                break;
            case '7':
                button7.doClick();
                break;
            case '8':
                button8.doClick();
                break;
            case '9':
                button9.doClick();
                break;
            case '-':
                buttonRest.doClick();
                break;
            case '+':
                buttonSum.doClick();
                break;
            case '/':
                buttonDiv.doClick();
                break;
            case '*':
                buttonMult.doClick();
                break;
            case '.':
                buttonDot.doClick();
                break;
            case '\n':
                buttonResult.doClick();
                break;
        }
        //delete last digit
        if (e.getKeyCode() == 8) {
            String text = screenField.getText();
            if (!isEmpty()) {
                text = text.substring(0, text.length() - 1);
                if (text.isEmpty()) {
                    screenField.setText("0");
                } else {
                    screenField.setText(text);
                }
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonDot;
    private javax.swing.JButton buttonMult;
    private javax.swing.JButton buttonRest;
    private javax.swing.JButton buttonResult;
    private javax.swing.JButton buttonSum;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JTextField screenField;
    // End of variables declaration//GEN-END:variables

}
